// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orion.DAL.EF.Models.DB;

namespace Orion.DAL.EF.Migrations
{
    [DbContext(typeof(OrionContext))]
    partial class OrionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Orion.DAL.EF.Models.DB.AccessGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccessGroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AccessGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessGroupName = "Admin",
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            AccessGroupName = "User",
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1
                        });
                });

            modelBuilder.Entity("Orion.DAL.EF.Models.DB.CapturedTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("CapturedTime");
                });

            modelBuilder.Entity("Orion.DAL.EF.Models.DB.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("Rate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            Rate = 25m,
                            RoleName = "Casual Employee Level 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            Rate = 50m,
                            RoleName = "Casual Employee Level 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            Rate = 50m,
                            RoleName = "Manager"
                        });
                });

            modelBuilder.Entity("Orion.DAL.EF.Models.DB.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("Duration")
                        .HasColumnType("decimal(18, 1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Duration = 1m,
                            IsDeleted = false,
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            TaskName = "Default Task"
                        });
                });

            modelBuilder.Entity("Orion.DAL.EF.Models.DB.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccessGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ChangePasswordOnNextLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastUpdatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("image");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessGroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessGroupId = 1,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "admin@admin.com",
                            EmployeeNumber = "XXXXXXXXX",
                            FirstName = "Root",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Admin",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 3,
                            UserName = "SuperUser"
                        },
                        new
                        {
                            Id = 2,
                            AccessGroupId = 1,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "jan.groenewald@orion.com",
                            EmployeeNumber = "EMP00001",
                            FirstName = "Jan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Groenewald",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 3,
                            UserName = "JGroenewald"
                        },
                        new
                        {
                            Id = 3,
                            AccessGroupId = 2,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "amanda.beukes@orion.com",
                            EmployeeNumber = "EMP00002",
                            FirstName = "Amanda",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Beukes",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 1,
                            UserName = "Amanda01"
                        },
                        new
                        {
                            Id = 4,
                            AccessGroupId = 2,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "Sandra.Swart@orion.com",
                            EmployeeNumber = "EMP00003",
                            FirstName = "Sandra",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Swart",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 2,
                            UserName = "SandyS"
                        },
                        new
                        {
                            Id = 5,
                            AccessGroupId = 2,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "Carl.Ross@orion.com",
                            EmployeeNumber = "EMP00004",
                            FirstName = "Carl",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Ross",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 2,
                            UserName = "Carl001"
                        },
                        new
                        {
                            Id = 6,
                            AccessGroupId = 2,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "Jackie.Oswalt@orion.com",
                            EmployeeNumber = "EMP00005",
                            FirstName = "Jackie",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Oswalt",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 1,
                            UserName = "JackieO"
                        },
                        new
                        {
                            Id = 7,
                            AccessGroupId = 1,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "Loy.McDonald@orion.com",
                            EmployeeNumber = "EMP00006",
                            FirstName = "Loy",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "McDonald",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 3,
                            UserName = "LMcD01"
                        },
                        new
                        {
                            Id = 8,
                            AccessGroupId = 2,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "Grace.Winters@orion.com",
                            EmployeeNumber = "EMP00007",
                            FirstName = "Grace",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Winters",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 2,
                            UserName = "Winters01"
                        },
                        new
                        {
                            Id = 9,
                            AccessGroupId = 2,
                            AppointmentDate = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            ChangePasswordOnNextLogin = false,
                            CreatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = 1,
                            Email = "Gert.Lombard@orion.com",
                            EmployeeNumber = "EMP00008",
                            FirstName = "Gert",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Lombard",
                            LastUpdatedAt = new DateTime(2020, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            LastUpdatedBy = 1,
                            LockoutEnabled = false,
                            PasswordHash = "CWa/NbR02Squq2Np65dn4Q==",
                            RoleId = 2,
                            UserName = "lombard01"
                        });
                });

            modelBuilder.Entity("Orion.DAL.EF.Models.DB.CapturedTime", b =>
                {
                    b.HasOne("Orion.DAL.EF.Models.DB.Task", "Task")
                        .WithMany("CapturedTime")
                        .HasForeignKey("TaskId")
                        .HasConstraintName("FK_CapturedTime_Task")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orion.DAL.EF.Models.DB.User", "User")
                        .WithMany("CapturedTime")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_CapturedTime_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orion.DAL.EF.Models.DB.User", b =>
                {
                    b.HasOne("Orion.DAL.EF.Models.DB.AccessGroup", "AccessGroup")
                        .WithMany("User")
                        .HasForeignKey("AccessGroupId")
                        .HasConstraintName("FK_User_AccessGroup");

                    b.HasOne("Orion.DAL.EF.Models.DB.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_User_Role");
                });
#pragma warning restore 612, 618
        }
    }
}
